export interface OpenLibraryCategory {
	value: string;
	name: string;
	values: string[];
	translations: string[];
	to?: string;
}

export const OPEN_LIBRARY_CATEGORIES: OpenLibraryCategory[] = [
	{
		value: "Home",
		name: "Anasayfa",
		values: ["New"],
		translations: ["Yeni Kitaplar"],
		to: "/",
	},
	{
		value: "Art",
		name: "Sanat",
		values: [
			"Architecture",
			"Art Instruction",
			"Art History",
			"Dance",
			"Design",
			"Fashion",
			"Film",
			"Graphic Design",
			"Music",
			"Music Theory",
			"Painting",
			"Photography",
		],
		translations: [
			"Mimarlık",
			"Sanat Eğitimi",
			"Sanat Tarihi",
			"Dans",
			"Tasarım",
			"Moda",
			"Film",
			"Grafik Tasarım",
			"Müzik",
			"Müzik Teorisi",
			"Resim",
			"Fotoğrafçılık",
		],
	},
	{
		value: "Animals",
		name: "Hayvanlar",
		values: ["Bears", "Cats", "Kittens", "Dogs", "Puppies"],
		translations: [
			"Ayılar",
			"Kediler",
			"Yavrular",
			"Köpekler",
			"Yavru Köpekler",
		],
	},
	{
		value: "Fiction",
		name: "Kurgu",
		values: [
			"Fantasy",
			"Historical Fiction",
			"Horror",
			"Humor",
			"Literature",
			"Magic",
			"Mystery and detective stories",
			"Plays",
			"Poetry",
			"Romance",
			"Science Fiction",
			"Short Stories",
			"Thriller",
			"Young Adult",
		],
		translations: [
			"Fantastik",
			"Tarihi Kurgu",
			"Korku",
			"Komedi",
			"Edebiyat",
			"Büyü",
			"Gizem ve dedektif hikayeleri",
			"Oyunlar",
			"Şiir",
			"Aşk",
			"Bilim Kurgu",
			"Kısa Hikayeler",
			"Gerilim",
			"Genç Yetişkin",
		],
	},
	{
		value: "Science & Mathematics",
		name: "Bilim ve Matematik",
		values: ["Biology", "Chemistry", "Mathematics", "Physics", "Programming"],
		translations: ["Biyoloji", "Kimya", "Matematik", "Fizik", "Programlama"],
	},
	{
		value: "Business & Finance",
		name: "İş ve Finans",
		values: [
			"Management",
			"Entrepreneurship",
			"Business Economics",
			"Business Success",
			"Finance",
		],
		translations: [
			"Yönetim",
			"Girişimcilik",
			"İş Ekonomisi",
			"İş Başarısı",
			"Finans",
		],
	},
	{
		value: "Children's",
		name: "Çocuk Kitapları",
		values: [
			"Kids Books",
			"Stories in Rhyme",
			"Baby Books",
			"Bedtime Books",
			"Picture Books",
		],
		translations: [
			"Çocuk Kitapları",
			"Kafiye Hikayeler",
			"Bebek Kitapları",
			"Uyku Öncesi Kitaplar",
			"Resimli Kitaplar",
		],
	},
	{
		value: "History",
		name: "Tarih",
		values: [
			"Ancient Civilization",
			"Archaeology",
			"Anthropology",
			"World War II",
			"Social Life and Customs",
		],
		translations: [
			"Antik Medeniyet",
			"Arkeoloji",
			"Antropoloji",
			"İkinci Dünya Savaşı",
			"Sosyal Hayat ve Gelenekler",
		],
	},
	{
		value: "Health & Wellness",
		name: "Sağlık ve Zindelik",
		values: [
			"Cooking",
			"Cookbooks",
			"Mental Health",
			"Exercise",
			"Nutrition",
			"Self-help",
		],
		translations: [
			"Yemek Pişirme",
			"Yemek Kitapları",
			"Zihinsel Sağlık",
			"Egzersiz",
			"Beslenme",
			"Kişisel Gelişim",
		],
	},
	{
		value: "Biography",
		name: "Biyografi",
		values: [
			"Autobiographies",
			"History",
			"Politics and Government",
			"World War II",
			"Women",
			"Kings and Rulers",
			"Composers",
			"Artists",
			"Anthropology",
			"Religion",
			"Political Science",
			"Psychology",
		],
		translations: [
			"Otomobiyografiler",
			"Tarih",
			"Politika ve Hükümet",
			"İkinci Dünya Savaşı",
			"Kadınlar",
			"Krallar ve Hükümdarlar",
			"Besteciler",
			"Sanatçılar",
			"Antropoloji",
			"Din",
			"Siyaset Bilimi",
			"Psikoloji",
		],
	},
	{
		value: "Places",
		name: "Yerler",
		values: ["Brazil", "India", "Indonesia", "United States"],
		translations: [
			"Brezilya",
			"Hindistan",
			"Endonezya",
			"Amerika Birleşik Devletleri",
		],
	},
	{
		value: "Textbooks",
		name: "Ders Kitapları",
		values: [
			"History",
			"Mathematics",
			"Geography",
			"Psychology",
			"Algebra",
			"Education",
			"Business & Economics",
			"Science",
			"Chemistry",
			"English Language",
			"Physics",
			"Computer Science",
		],
		translations: [
			"Tarih",
			"Matematik",
			"Coğrafya",
			"Psikoloji",
			"Cebir",
			"Eğitim",
			"İş ve Ekonomi",
			"Bilim",
			"Kimya",
			"İngilizce",
			"Fizik",
			"Bilgisayar Bilimi",
		],
	},
];
